# numpy
numpy 用於處理陣列、矩陣或張量式的資料非常好用

## 載入 numpy

In [1]:
import numpy as np

## 創建 ndarray 張量

#### np.array()

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### np.arange()


In [5]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### np.linspace()

In [11]:
a = np.linspace(1,10,100)
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

#### np.zeros(), np.ones(), np.zeros_like(), np.ones_like()

In [15]:
a = np.zeros([3,3])
b = np.ones([3,3,3])

aa = np.zeros_like(a)
bb = np.ones_like(b)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### np.random.uniform(), np.random.normal()

In [20]:
a = np.random.uniform(0,1,2)
b = np.random.normal(0,1,2)
print(a)

[0.72584258 0.81700859]


## 向量、矩陣相乘

#### 向量內積

In [22]:
a = np.array([1,2,3])
b = np.array([3,2,1])
c = a@b
print(c)

10


#### 矩陣相乘

In [26]:
a = np.array([[1,2],[3,2]])
b = np.array([[3,2],[1,2]])
c = a@b
print(c)

[[ 5  6]
 [11 10]]


## 反矩陣

In [28]:
a = np.array([[1,2],[3,2]])
b = np.linalg.inv(a)
print(b)

[[-0.5   0.5 ]
 [ 0.75 -0.25]]


#### 擬反矩陣

In [29]:
a = np.array([[0,1,2],[3,4,5],[0,2,4]])
b = np.linalg.pinv(a)
print(b)

[[-0.15555556  0.27777778 -0.31111111]
 [-0.02222222  0.11111111 -0.04444444]
 [ 0.11111111 -0.05555556  0.22222222]]


## 補充

copy

In [4]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 5
print(a)
print(b)

[1 2 3]
[5 2 3]


#### 張量重新排列

In [11]:
a = np.arange(6)
print(a)

b = np.reshape(a,(3,2))
print(b)

c = np.reshape(a,(3,-1))
print(c)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


#### 張量拼接

#### .all() .any()